<?php

/**
 * PluginmdBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mdBannerDoctrinePlugin
 * @subpackage model
 * @author     Gaston Caldeiro <chugas488@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdBanner extends BasemdBanner {
  const SF_CACHE_KEY = 'mdbanner';

  const FOLDER_NAME = 'banners';

  /**
   * Devuelve el path absoluto de el archivo
   * 
   * @return string
   */
  public function getPath() {
    if ($this->getFilename() == '')
      return sfConfig::get('sf_web_dir') . '/' . self::FOLDER_NAME . '/no-image.jpg';

    if ($this->isSwf()) {

      return sfConfig::get('sf_web_dir') . '/' . self::FOLDER_NAME . '/' . $this->getFilename();
    } else {

      return sfConfig::get('sf_upload_dir') . '/' . self::FOLDER_NAME . '/' . $this->getFilename();
    }
  }

  /**
   * Devuelve la ruta a partir de /uploads para el caso de imagenes
   * 
   * @return string
   */
  public function getSrc() {
    if ($this->getFilename() == '')
      return '/mdBannerDoctrinePlugin/images/no-image.jpg';

    if ($this->isSwf()) {

      return '/' . self::FOLDER_NAME . '/' . $this->getFilename();
    } else {

      return '/' . self::FOLDER_NAME . '/' . $this->getFilename();
    }
  }

  /**
   * Devuelve la ruta a partir para cualquier tipo de archivo
   * 
   * @return string
   */
  public function getSrcImage() {
    if ($this->getFilename() == '')
      return '/mdBannerDoctrinePlugin/images/no-image.jpg';

    if ($this->isSwf()) {

      return "/mdBannerDoctrinePlugin/images/swf.jpg";
    } else {

      return '/uploads/' . self::FOLDER_NAME . '/' . $this->getFilename();
    }
  }
  
  public function getPartialName() {
    if ($this->isSwf()) {

      return 'mdBannerSwf';
    } else {

      return 'mdBannerImage';
    }
  }

  public function isSwf() {
    return (strpos($this->getFilename(), '.swf') !== false);
  }

  public function postSave($event) {
    // Limpiamos cache
    $command = 'find ' . sfConfig::get('sf_cache_dir') . ' -name "' . self::SF_CACHE_KEY . '_' . '"* -exec rm -rf {} \;';
    exec($command);

    /* sfContext::getInstance()->switchTo('frontend');
      if ($cache = sfContext::getInstance()->getViewCacheManager()) {
      $cache->remove('@sf_cache_partial?module=sales&action=_voceSabia&sf_cache_key=vocesabia-listado');
      }
      sfContext::getInstance()->switchTo('backend'); */
  }

}